# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/permalinks/" # the subpath of your site, e.g. /blog/
url: "http://tseivan.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: /:categories/:year/:month/:day/:title/

# Build settings
markdown: kramdown
